### ISSUE TITLE
salt '*' state.highstate 错误

### ISSUE THREAD

**Issue by yekeqiang** [pengyao/salt-zabbix#3]
在执行 salt '*' state.highstate 的时候，43个项目，错误10个，看了下日志，是在mysql的用户那块的时候失败的，要求必须要存在mysql的用户，用户名为zabbix，但是我这边已经创建了zabbix库，以及创建了zabbix用户，并且让其能访问zabbix库了
## 版本是2014.1.5

```
      ID: zabbix_mysql
Function: mysql_database.present
    Name: zabbix
  Result: False
 Comment: State mysql_database.present found in sls zabbix.server is unavailable
 Changes:   
```

---

```
      ID: zabbix_mysql
Function: mysql_user.present
    Name: zabbix
  Result: False
 Comment: One or more requisite failed
 Changes:   
```

---

```
      ID: zabbix_mysql
Function: mysql_grants.present
  Result: False
 Comment: One or more requisite failed
 Changes:   
```

---
